<plugin>
    <groupId>com.lazerycode.jmeter</groupId>
    <artifactId>jmeter-maven-plugin</artifactId>
    <version>3.3.0</version>
    <executions>
        <execution>
            <id>jmeter-tests</id>
            <goals>
                <goal>jmeter</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <!-- 添加 JMeter WebDriver 插件依赖 -->
        <dependency>
            <groupId>kg.apc</groupId>
            <artifactId>jmeter-plugins-webdriver</artifactId>
            <version>3.3</version>
        </dependency>
    </dependencies>
</plugin>